import { memo } from 'react';
import Svg, { Path } from 'react-native-svg';
import { iconNames, type IconName } from '@da/design-tokens';
import { GLYPHS } from '../icons/glyphs';
import { useTheme } from '../theme/ThemeProvider';

export interface IconProps {
  name: IconName;
  /** 16 · 18 · 20 (default) · 22 · 24 · 26 */
  size?: number;
  color?: string;
  /** FILL 1 variant (active tab, AI mark, completed). */
  filled?: boolean;
  accessibilityLabel?: string;
  style?: object;
}

/**
 * Material Symbols Rounded glyphs (wght 400) rendered as SVG paths — exact match to the design,
 * without shipping the full icon font. Glyph paths are generated by scripts/fetch-material-symbols.mjs.
 */
export const Icon = memo(function Icon({ name, size = 20, color, filled = false, accessibilityLabel, style }: IconProps) {
  const theme = useTheme();
  const glyphName = iconNames[name];
  const glyph = GLYPHS[glyphName];
  const fill = color ?? theme.colors.ink;
  if (!glyph) {
    return <Svg width={size} height={size} viewBox="0 0 24 24" style={style} />;
  }
  const variant = filled && glyph.fill ? glyph.fill : glyph.outline;
  return (
    <Svg
      width={size}
      height={size}
      viewBox={variant.viewBox}
      style={style}
      accessibilityLabel={accessibilityLabel}
      accessibilityRole={accessibilityLabel ? 'image' : undefined}
      accessible={Boolean(accessibilityLabel)}
      importantForAccessibility={accessibilityLabel ? 'yes' : 'no-hide-descendants'}
    >
      <Path d={variant.d} fill={fill} />
    </Svg>
  );
});
