/** Stable TanStack Query keys shared by every screen (invalidate by prefix). */
export const qk = {
  session: ['session'] as const,
  profile: ['profile'] as const,
  preferences: ['preferences'] as const,
  notificationPreferences: ['notificationPreferences'] as const,
  entitlement: ['entitlement'] as const,
  accounts: ['accounts'] as const,
  today: (date?: string) => ['today', date ?? 'now'] as const,
  flow: (filter: string) => ['flow', filter] as const,
  insight: (id: string) => ['insight', id] as const,
  mailIntelligence: ['mailIntelligence'] as const,
  waiting: ['waiting'] as const,
  lifeEvents: ['lifeEvents'] as const,
  lifeEvent: (id: string) => ['lifeEvent', id] as const,
  thread: (id: string) => ['thread', id] as const,
  followUps: ['followUps'] as const,
  followUp: (id: string) => ['followUp', id] as const,
  plan: (date: string, range: string) => ['plan', date, range] as const,
  tasks: ['tasks'] as const,
  commitments: ['commitments'] as const,
  commitment: (id: string) => ['commitment', id] as const,
  conflicts: ['conflicts'] as const,
  conflict: (id: string) => ['conflict', id] as const,
  event: (id: string) => ['event', id] as const,
  events: (from: string, to: string) => ['events', from, to] as const,
  meetingPrep: (eventId: string) => ['meetingPrep', eventId] as const,
  recentlyEnded: ['recentlyEnded'] as const,
  approvals: (statuses?: string[]) => ['approvals', ...(statuses ?? ['all'])] as const,
  approval: (id: string) => ['approval', id] as const,
  approvalsPending: ['approvals', 'pendingCount'] as const,
  reminders: ['reminders'] as const,
  reminderSuggest: (targetType: string, targetId: string) =>
    ['reminderSuggest', targetType, targetId] as const,
  assistantThreads: ['assistantThreads'] as const,
  assistantMessages: (threadId: string) => ['assistantMessages', threadId] as const,
  suggestedQuestions: (contactId?: string | null) =>
    ['suggestedQuestions', contactId ?? 'global'] as const,
  search: (q: string) => ['search', q] as const,
  recentQueries: ['recentQueries'] as const,
  captures: ['captures'] as const,
  capture: (id: string) => ['capture', id] as const,
  contacts: (q?: string) => ['contacts', q ?? ''] as const,
  person: (id: string) => ['person', id] as const,
  vips: ['vips'] as const,
  rules: ['rules'] as const,
  learned: ['learned'] as const,
  briefing: (kind: string, date?: string) => ['briefing', kind, date ?? 'today'] as const,
  briefingById: (id: string) => ['briefingById', id] as const,
  briefingAudio: (id: string) => ['briefingAudio', id] as const,
  weekly: (weekStart?: string) => ['weekly', weekStart ?? 'current'] as const,
  subscriptions: ['subscriptions'] as const,
  referral: ['referral'] as const,
  exportStatus: ['exportStatus'] as const,
  auditLogs: ['auditLogs'] as const,
  androidNotifications: ['androidNotifications'] as const,
  firstAnalysis: ['firstAnalysis'] as const,
} as const;
