/** Deterministic content signals (Turkish + English). All regexes run on lowercase text. */
import { flexI, lowercasePreservingIndices } from '../dates';

const B = '(?<![\\p{L}\\p{N}])';
const E = '(?![\\p{L}\\p{N}])';

/** Bounded Turkish inflection allowed after a keyword ("cihazdan", "şifresi", "kodunuz") — never "girişim". */
const INFLECTION = flexI("(?:'?(?:ndan|nden|dan|den|tan|ten|nda|nde|da|de|ta|te|ını|ini|unu|ünü|ınız|iniz|unuz|ünüz|nız|niz|nuz|nüz|ları|leri|lar|ler|ya|ye|sı|si|su|sü|na|ne|nı|ni|ı|i|u|ü|a|e|n))?");

function alternationOf(list: string[]): string {
  return [...list]
    .sort((a, b) => b.length - a.length)
    .map((w) => flexI(w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
    .join('|');
}

function words(list: string[]): RegExp {
  return new RegExp(`${B}(?:${alternationOf(list)})${E}`, 'u');
}

function wordsInflected(list: string[]): RegExp {
  return new RegExp(`${B}(?:${alternationOf(list)})${INFLECTION}${E}`, 'u');
}

export const RE_PROMO = words([
  'indirim',
  'indirimli',
  'kampanya',
  'kampanyalar',
  'fırsat',
  'fırsatlar',
  'fırsatı',
  'kupon',
  'kuponunuz',
  'unsubscribe',
  'newsletter',
  'bülten',
  'e-bülten',
  'ebülten',
  'sale',
  'deal',
  'deals',
  'black friday',
  'sepetinizde',
  'sepetinde',
  'özel teklif',
  'sadece bugün',
  'kaçırma',
  'kaçırmayın',
  'yeni sezon',
  'ücretsiz kargo',
  'bedava',
  'hediye çeki',
  'promo',
  'promosyon',
  'sana özel',
  'size özel',
  'abonelikten çık',
  'aboneliği iptal',
]);
export const RE_PERCENT = /(?:%\s?\d{1,3}|\d{1,3}\s?%)/u;

export const RE_MEETING = words([
  'toplantı',
  'toplantısı',
  'toplantıya',
  'toplantımız',
  'meeting',
  'görüşme',
  'görüşmemiz',
  'davet',
  'davetiye',
  'invitation',
  'invite',
  'invited',
  'zoom',
  'google meet',
  'meet.google.com',
  'microsoft teams',
  'teams',
  'randevu',
  'randevunuz',
  'takvim daveti',
  'calendar invitation',
  'webinar',
  'call',
  'görüşelim',
  'buluşalım',
  'buluşma',
]);

export const RE_SECURITY_STRONG = wordsInflected([
  'yeni giriş',
  'yeni bir giriş',
  'yeni cihaz',
  'yeni bir cihaz',
  'new sign-in',
  'new sign in',
  'new login',
  'new device',
  'şifreniz değiştirildi',
  'şifre değişikliği',
  'şifreniz sıfırlandı',
  'şifre sıfırlama',
  'şifrenizi sıfırlayın',
  'şifrenizi sıfırlamak',
  'şifreniz güncellendi',
  'parolanız değiştirildi',
  'parola sıfırlama',
  'password changed',
  'password was changed',
  'password reset',
  'reset your password',
  'password change',
  'doğrulama kodu',
  'doğrulama kodunuz',
  'onay kodu',
  'onay kodunuz',
  'giriş kodu',
  'giriş kodunuz',
  'güvenlik kodu',
  'güvenlik kodunuz',
  'verification code',
  'security code',
  'login code',
  'one-time code',
  'one-time password',
  'tek kullanımlık',
  'otp',
  '2fa',
  'iki adımlı',
  'iki faktörlü',
  'two-factor',
  'two-step',
  'güvenlik uyarısı',
  'security alert',
  'critical security alert',
  'şüpheli giriş',
  'şüpheli etkinlik',
  'şüpheli hareket',
  'suspicious sign-in',
  'suspicious activity',
  'suspicious login',
  'unusual activity',
  'unusual sign-in',
  'olağandışı etkinlik',
  'hesabınıza giriş yapıldı',
  'hesabınıza erişim',
  'hesabına giriş yapıldı',
  'signed in to your',
  'was used to sign in',
  'kurtarma e-postası',
  'kurtarma telefonu',
  'recovery email',
  'recovery phone',
  'hesabınızın güvenliği',
  'hesap güvenliği',
  'account security',
]);
export const RE_SECURITY_WEAK = wordsInflected(['şifre', 'şifreniz', 'parola', 'password', 'giriş yapıldı', 'oturum açıldı', 'signed in']);
export const RE_OTP = wordsInflected([
  'doğrulama kodu',
  'doğrulama kodunuz',
  'onay kodu',
  'onay kodunuz',
  'giriş kodu',
  'giriş kodunuz',
  'güvenlik kodu',
  'güvenlik kodunuz',
  'verification code',
  'security code',
  'login code',
  'one-time code',
  'one-time password',
  'tek kullanımlık',
  'otp',
  'passcode',
  'your code',
  'kodunuz',
]);
export const RE_SECURITY_EVENT_CRITICAL = wordsInflected([
  'yeni giriş',
  'yeni bir giriş',
  'yeni cihaz',
  'yeni bir cihaz',
  'new sign-in',
  'new sign in',
  'new login',
  'new device',
  'şifreniz değiştirildi',
  'şifre değişikliği',
  'parolanız değiştirildi',
  'password changed',
  'password was changed',
  'şüpheli giriş',
  'suspicious sign-in',
  'suspicious login',
  'critical security alert',
  'hesabınıza giriş yapıldı',
  'hesabına giriş yapıldı',
  'was used to sign in',
]);

export const RE_FINANCE = words([
  'fatura',
  'faturanız',
  'faturası',
  'faturalar',
  'e-fatura',
  'e-arşiv',
  'invoice',
  'ödeme',
  'ödemeniz',
  'ödemesi',
  'ödenmemiş',
  'ödendi',
  'payment',
  'payment due',
  'amount due',
  'borç',
  'borcunuz',
  'ekstre',
  'ekstreniz',
  'statement',
  'dekont',
  'tahsilat',
  'son ödeme',
  'vade',
  'havale',
  'eft',
  'kredi kartı',
  'makbuz',
  'receipt',
  'tutar',
  'taksit',
  'aidat',
  'kira',
]);
export const RE_AMOUNT = /(?:\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?\s?(?:tl|₺|try)(?![\p{L}])|₺\s?\d|\$\s?\d|\d(?:[.,]\d+)?\s?(?:usd|eur|€|gbp|£)(?![\p{L}])|€\s?\d|£\s?\d)/u;

export const RE_TRAVEL = words([
  'uçuş',
  'uçuşunuz',
  'uçuş bilgileri',
  'flight',
  'flights',
  'pnr',
  'boarding',
  'boarding pass',
  'biniş kartı',
  'e-bilet',
  'e-ticket',
  'itinerary',
  'thy',
  'türk hava yolları',
  'turkish airlines',
  'pegasus',
  'ajet',
  'sunexpress',
  'anadolujet',
  'rezervasyon',
  'rezervasyonunuz',
  'reservation',
  'booking',
  'check-in',
  'checkin',
  'otel',
  'hotel',
  'konaklama',
  'seyahat',
  'gate',
  'kalkış',
  'varış',
  'departure',
  'arrival',
  'airbnb',
  'booking.com',
  'obilet',
  'bilet',
  'biletiniz',
  'lufthansa',
  'ryanair',
  'wizz air',
]);

export const RE_SHIPMENT = words([
  'kargo',
  'kargonuz',
  'kargoya verildi',
  'kargoda',
  'kargoya',
  'teslimat',
  'teslimatı',
  'teslim edildi',
  'teslim edilecek',
  'dağıtıma çıktı',
  'dağıtımda',
  'takip numarası',
  'takip numaranız',
  'takip no',
  'kargo takip',
  'tracking number',
  'tracking no',
  'tracking id',
  'gönderi',
  'gönderiniz',
  'shipment',
  'shipped',
  'delivered',
  'out for delivery',
  'siparişiniz',
  'siparişin',
  'sipariş',
  'your order',
  'order shipped',
  'yurtiçi',
  'yurtiçi kargo',
  'aras kargo',
  'aras',
  'mng',
  'mng kargo',
  'sürat kargo',
  'ptt kargo',
  'ups',
  'dhl',
  'fedex',
  'hepsijet',
  'trendyol express',
  'kolay gelsin',
  'sendeo',
  'trendyol',
  'hepsiburada',
  'amazon',
  'n11',
  'getir',
  'çiçeksepeti',
  'yola çıktı',
  'paketiniz',
  'paketin',
]);

export const RE_SUBSCRIPTION = words([
  'abonelik',
  'aboneliğiniz',
  'aboneliğin',
  'subscription',
  'yenilenecek',
  'yenilenecektir',
  'yenileniyor',
  'yenileme',
  'renew',
  'renews',
  'renewal',
  'will renew',
  'üyeliğiniz',
  'üyeliğin',
  'membership',
  'deneme süresi',
  'deneme süreniz',
  'trial',
  'otomatik yenileme',
  'auto-renew',
  'auto-renewal',
  'faturalandırılacak',
  'will be charged',
]);

export const RE_ASKS_USER = /\?|(?<![\p{L}])(?:misin|mısın|musun|müsün|misiniz|mısınız|musunuz|müsünüz|rica ederim|rica ediyorum|rica ederiz|lütfen|please|could you|can you|would you|bekliyorum|bekliyoruz|geri dönüş|onayınızı|onaylar mısınız|görüşünüzü|ne dersin|ne dersiniz)(?![\p{L}])/u;

export const RE_AUTO_REPLY_SUBJECT = words([
  'out of office',
  'automatic reply',
  'auto reply',
  'auto-reply',
  'otomatik yanıt',
  'otomatik cevap',
  'ofis dışındayım',
  'ofis dışı',
  'yıllık izin',
  'izindeyim',
]);

export function normalizeForSignals(text: string): string {
  return lowercasePreservingIndices(text);
}
